SELECT APNT_NO, PT_NAME, P.PT_NO, A.MCDP_CD, DR_NAME, APNT_YMD
FROM PATIENT P JOIN APPOINTMENT A 
ON P.PT_NO = A.PT_NO
JOIN DOCTOR D
ON D.DR_ID = A.MDDR_ID
WHERE APNT_CNCL_YN = 'N' AND DATE_FORMAT(DATE(APNT_YMD), '%Y%m%d') = '20220413'
ORDER BY APNT_YMD